enum COLORS {
  BACKGROUND = 'BACKGROUND',
  PRIMARY = 'PRIMARY',
  BORDER_COLOR = 'BORDER_COLOR',
  DISABLED_ELEMENT_BORDER = 'DISABLED_ELEMENT_BORDER',
  OUTLINED_ELEMENT_BORDER = 'OUTLINED_ELEMENT_BORDER',
  DANGER = 'DANGER',
  DEFAULT = 'DEFAULT',
}

export { COLORS };
