enum SPACES {
  SPACE_ZERO = 'SPACE_ZERO',
  SPACE_EXTRA_TINY = 'SPACE_EXTRA_TINY',
  SPACE_TINY = 'SPACE_TINY',
  SPACE_SMALL = 'SPACE_SMALL',
  SPACE_MEDIUM = 'SPACE_MEDIUM',
  SPACE_BASE = 'SPACE_BASE',
  SPACE_LARGE = 'SPACE_LARGE',
  SPACE_BIG = 'SPACE_BIG',
  SPACE_EXTRA_BIG = 'SPACE_EXTRA_BIG',
}

export { SPACES };
