enum FONTS {
  BASE = 'BASE',
}

enum FONT_SIZES {
  EXTRA_SMALL = 'EXTRA_SMALL',
  SMALL = 'SMALL',
  BASE = 'BASE',
  LARGE_BASE = 'LARGE_BASE',
  LARGE = 'LARGE',
  EXTRA_LARGE = 'EXTRA_LARGE',
  EXTRA_EXTRA_LARGE = 'EXTRA_EXTRA_LARGE',
  GIANT = 'GIANT',
}

enum FONT_HEIGHTS {
  BASE = 'BASE',
  SMALL = 'SMALL',
  LARGE = 'LARGE',
}

enum LINE_HEIGHTS {
  EXTRA_SMALL = 'EXTRA_SMALL',
  BASE = 'BASE',
  SMALL = 'SMALL',
  LARGE = 'LARGE',
  EXTRA_LARGE = 'EXTRA_LARGE',
  EXTRA_EXTRA_LARGE = 'EXTRA_EXTRA_LARGE',
  EXTRA_EXTRA_SMALL = 'EXTRA_EXTRA_SMALL',
  EXTRA_EXTRA_EXTRA_SMALL = 'EXTRA_EXTRA_EXTRA_SMALL',
  GIANT = 'GIANT',
}
enum FONT_WEIGHTS {
  BASE = 'BASE',
  SEMI_BOLD = 'SEMI_BOLD',
  BOLD = 'BOLD',
  EXTRA_BOLD = 'EXTRA_BOLD',
}

export { FONTS, FONT_WEIGHTS, FONT_SIZES, FONT_HEIGHTS, LINE_HEIGHTS };
