const AUTH = {
  LOGIN: '@@auth/LOGIN',
  LOGIN_LOADING: '@@auth/LOGIN_LOADING',
  LOGIN_SUCCESS: '@@auth/LOGIN_SUCCESS',
  LOGIN_FAILURE: '@@auth/LOGIN_FAILURE',

  REGISTER: '@@auth/REGISTER',
  REGISTER_LOADING: '@@auth/REGISTER_LOADING',
  REGISTER_SUCCESS: '@@auth/REGISTER_SUCCESS',
  REGISTER_FAILURE: '@@auth/REGISTER_FAILURE',

  LOGOUT: '@@auth/LOGOUT',
  LOGOUT_LOADING: '@@auth/LOGOUT_LOADING',
  LOGOUT_SUCCESS: '@@auth/LOGOUT_SUCCESS',
  LOGOUT_FAILURE: '@@auth/LOGOUT_FAILURE',

  SET_TOKEN: '@@auth/SET_TOKEN',

  SET_EMAIL: '@@auth/SET_EMAIL',

  RESET_AUTH: '@@auth/RESET_AUTH',

  RESET_AUTH_ERROR: '@@auth/RESET_AUTH_ERROR',

  RESET_AUTH_STATE: '@@auth/RESET_AUTH_STATE',
};

export { AUTH };
