const AUTH = {
  LOGIN: '@@auth/LOGIN',
  LOGIN_LOADING: '@@auth/LOGIN_LOADING',
  LOGIN_SUCCESS: '@@auth/LOGIN_SUCCESS',
  LOGIN_FAILURE: '@@auth/LOGIN_FAILURE',

  RESET_AUTH_STATE: '@@auth/RESET_AUTH_STATE',
};

export { AUTH };
