const TEST_EMAIL = 'TEST_EMAIL';

const TEST_PASSWORD = 'TEST_PASSWORD';

const TEST_ID = 1;

const TEST_TOKEN = 'TEST_TOKEN';

const TEST_ERROR_MESSAGE = 'TEST_ERROR_MESSAGE';

const TEST_ERROR = {
  message: TEST_ERROR_MESSAGE,
};

export { TEST_PASSWORD, TEST_EMAIL, TEST_TOKEN, TEST_ID, TEST_ERROR };
