const TEST_EMAIL = 'TEST_EMAIL';

const TEST_PASSWORD = 'TEST_PASSWORD';

const TEST_DATA_STRING = 'TEST_DATA_STRING';

const TEST_ID = 1;

const TEST_BOOL_TRUE = true;

const TEST_BOOL_FALSE = false;

const TEST_TOKEN = 'TEST_TOKEN';

const TEST_ERROR_MESSAGE = 'TEST_ERROR_MESSAGE';

const TEST_ERROR = {
  message: TEST_ERROR_MESSAGE,
};

export {
  TEST_BOOL_FALSE,
  TEST_BOOL_TRUE,
  TEST_PASSWORD,
  TEST_EMAIL,
  TEST_TOKEN,
  TEST_ID,
  TEST_ERROR,
  TEST_DATA_STRING,
};
